#pragma once

// default value for various settings
#define DEFAULT_AUTO_START false
#define DEFAULT_CHECK_FOR_UPDATES_AT_STARTUP true
#define DEFAULT_PERIOD daily
#define DEFAULT_ADJUST true
#define DEFAULT_ALL_AVAILABLE false
#define DEFAULT_UPDATE false
#define DEFAULT_VALIDATE_PRICES true
#define DEFAULT_SORT_BARS_ASCENDING true
#define DEFAULT_DATE_FORMAT yloader::us
#define DEFAULT_ADD_SYMBOL false
#define DEFAULT_COLUMN_NUMBER 0
#define DEFAULT_EXTENSION _T( "csv" )
#define DEFAULT_PAD_DATE_FIELDS false
#define DEFAULT_SYMBOL_TIMEOUT 30
#define DEFAULT_CREATE_SUBDIRS false
#define DEFAULT_THREADS 5
#define MAX_THREADS 20
#define DEFAULT_AUTO_SELECT_OUTPUT_PATH false
#define DEFAULT_FIELD_SEPARATOR _T( "," )
#define DEFAULT_VOLUME_MULTIPLIER 1
#define DEFAULT_FILE_HEADER _T( "" )
#define DEFAULT_SAVE_FILE_ALL _T( "" )
#define DEFAULT_DONT_RELOAD_DATA_IN_UPDATE_MODE false
#define DEFAULT_HANDLING_INVALID_DATA 0
#define DEFAULT_VOLUME0_INVALID 0
#define DEFAULT_DATE_SEPARATOR _T( "/" )
#define DEFAULT_APPEND_TO_LOG false
#define DEFAULT_LOG_ONLY_ERRORS true
#define DEFAULT_PROGRESS 100
#define DEFAULT_REGEX_FLAGS 0
#define DEFAULT_MATCH_REGEX _T( "(.*),(.*)/(.*)/(.*),(.*),(.*),(.*),(.*),(.*)" )
#define DEFAULT_FORMAT_STRING _T( "$1,$2/$3/$4,$5,$6,$7,$8,$9" )
#define DEFAULT_ENABLE_REGEX_FORMATTING false
#define DEFAULT_MATCH_REGEX_UNLOCKED false
#define DEFAULT_ERROR_SYMBOLS_LIST _T( "" )
#define DEFAULT_APPEND_TO_ERROR_SYMBOLS_LIST true
#define DEFAULT_IGNORE_ERROR_SYMBOLS_LIST true
#define DEFAULT_IGNORE_SYMBOLS_LIST _T( "" )
#define DEFAULT_DO_NOT_CHECK_FOR_UPDATE false
